export interface VideoChallenge {
  id: string;
  emoji: string;
  title: string;
  desc: string;
  instructionsBefore: string;
  instructionsAfter: string;
  tags: string[];
}

export const CHALLENGES: VideoChallenge[] = [
  {
    id: 'passeggiata',
    emoji: '📱',
    title: 'La Passeggiata',
    desc: 'Telefono a terra, camminata mano nella mano: prima da fidanzati, poi da sposati',
    instructionsBefore: 'Appoggia il telefono a terra (o su un gradino). Allontanatevi e poi camminate mano nella mano verso la telecamera. Sguardo complice ❤️',
    instructionsAfter: 'Rifate la stessa identica camminata durante la cerimonia. Stessa angolazione, stessa distanza, stessi sorrisi... ma ora siete marito e moglie!',
    tags: ['emozionante', 'facile'],
  },
  {
    id: 'corsa',
    emoji: '🏃',
    title: 'La Corsa',
    desc: 'Correte l\'uno verso l\'altra e abbracciatevi al rallentatore',
    instructionsBefore: 'Inquadratura laterale. Partite da lontano e correte verso l\'altro. L\'abbraccio finale deve essere cinematografico 🎬',
    instructionsAfter: 'Stessa inquadratura, stessa corsa, ma ora con gli abiti da cerimonia. Rallentate il momento dell\'abbraccio!',
    tags: ['divertente', 'facile'],
  },
  {
    id: 'primo-sguardo',
    emoji: '👀',
    title: 'Il Primo Sguardo',
    desc: 'Lui/lei vede l\'altro in abito nuziale per la prima volta: reazione genuina',
    instructionsBefore: 'Uno dei due è girato. L\'altro arriva da dietro e dice "Girati". Reazione spontanea alla prima volta che vi vedete eleganti!',
    instructionsAfter: 'Durante la cerimonia, riprendete lo stesso momento in cui vi guardate per la prima volta all\'altare. Stessa emozione, moltiplicata per mille!',
    tags: ['emozionante', 'consigliato'],
  },
  {
    id: 'abbraccio-dietro',
    emoji: '🤗',
    title: 'L\'Abbraccio a Sorpresa',
    desc: 'Uno abbraccia l\'altro da dietro mentre è distratto — la reazione è tutto',
    instructionsBefore: 'Uno dei due guarda lontano (tipo il panorama). L\'altro arriva silenziosamente da dietro e lo abbraccia. Cercate di non ridere!',
    instructionsAfter: 'Stessa scena durante la cerimonia: lei/lui guarda lontano, l\'altro arriva e abbraccia. La reazione sarà ancora più dolce con l\'abito da sposa!',
    tags: ['dolce', 'facile'],
  },
  {
    id: 'bacio-soglia',
    emoji: '💋',
    title: 'Il Bacio sulla Soglia',
    desc: 'Varcate una porta/soglia e fermatevi per un bacio — come nei film',
    instructionsBefore: 'Inquadratura frontale di una porta. Entrate insieme, fate due passi e fermatevi per un bacio. Sguardo in camera prima di baciarsi 😘',
    instructionsAfter: 'Riprendete la stessa scena all\'uscita dalla chiesa/location. Varcate la soglia da sposati e replicate il bacio. Effetto brividi!',
    tags: ['romantico', 'consigliato'],
  },
  {
    id: 'giro',
    emoji: '💃',
    title: 'Il Giro di Valzer',
    desc: 'Lui fa girare lei come in un ballo — eleganza e complicità',
    instructionsBefore: 'Inquadratura campo medio. Lui prende la mano di lei, la fa girare una volta e la riporta a sé. Sorrisi e sguardo negli occhi.',
    instructionsAfter: 'Stessa inquadratura, stesso giro, ma ora con l\'abito da sposa che volteggia. Ancora più magico!',
    tags: ['elegante', 'facile'],
  },
  {
    id: 'tortata',
    emoji: '🎂',
    title: 'La Tortata',
    desc: 'Prima elegantemente... poi vi sporcate di torta. Dal rischio al caos!',
    instructionsBefore: 'Inquadratura da vicino. Prendete un pezzo di torta, offritelo elegantemente all\'altro... e all\'ultimo secondo sporcategli il naso! 😂',
    instructionsAfter: 'Durante la cerimonia, rifate la stessa scena con la torta nuziale. Stessa dinamica, stesso caos, ma 100x più memorabile!',
    tags: ['divertente', 'caos'],
  },
  {
    id: 'firmana',
    emoji: '📝',
    title: 'La Firmana',
    desc: 'Firmate i documenti: confronto tra prove burocratiche e firma ufficiale',
    instructionsBefore: 'Inquadratura del tavolo. Sedetvi e fingete di firmare documenti serissimi. Sguardi complici, magari una risata di nascosto.',
    instructionsAfter: 'Riprendete la firma vera dei documenti in comune o in chiesa. Stessa inquadratura, stessa scrivania, ma firmate per davvero!',
    tags: [' originale', 'facile'],
  },
  {
    id: 'ingresso',
    emoji: '⛪',
    title: 'L\'Ingresso',
    desc: 'Entrate in chiesa/location: prove generali vs il giorno del SI',
    instructionsBefore: 'Inquadratura dall\'interno della chiesa/location. Entrate dalla porta principale e camminate verso l\'altare. Sguardi emozionati.',
    instructionsAfter: 'L\'ingresso vero: stessa inquadratura, stessa camminata, ma stavolta è tutto reale. Brividi garantiti!',
    tags: ['emozionante', 'consigliato'],
  },
  {
    id: 'macchina',
    emoji: '🚗',
    title: 'La Partenza',
    desc: 'Salite in macchina e partite verso l\'avventura — con stile',
    instructionsBefore: 'Inquadratura laterale della macchina. Aprite la portiera, salite, guardatevi e sorridete. Poi partite (anche solo 2 metri!).',
    instructionsAfter: 'Rifate la stessa scena con la macchina addobbata per il matrimonio. Stessi gesti, stessa complicità, auto più bella!',
    tags: ['divertente', 'facile'],
  },
  {
    id: 'lancio-bouquet',
    emoji: '💐',
    title: 'Il Lancio del Bouquet',
    desc: 'La sposa lancia il bouquet: prove con le amiche vs il lancio vero',
    instructionsBefore: 'Inquadratura alle spalle della sposa. Lei fa finta di lanciare il bouquet verso le amiche immaginarie. Girare la testa e ridere!',
    instructionsAfter: 'Il lancio vero! Stessa inquadratura, ma stavolta le amiche ci sono davvero e il bouquet vola per davvero. Chi lo prenderà?',
    tags: ['divertente', 'amiche'],
  },
  {
    id: 'prima-canzone',
    emoji: '🎵',
    title: 'La Prima Canzone',
    desc: '10 secondi del primo ballo — prove generali vs il momento magico',
    instructionsBefore: 'Inquadratura dal basso o laterale. Ballate 10 secondi della vostra canzone. Lui guarda lei, lei sorride. Movimenti semplici.',
    instructionsAfter: 'Durante il ricevimento, replicate gli stessi 10 secondi del primo ballo. Stessa inquadratura, stessi movimenti, ma l\'emozione è vera!',
    tags: ['romantico', 'consigliato'],
  },
  {
    id: 'testimoni',
    emoji: '🤝',
    title: 'Il Saluto ai Testimoni',
    desc: 'Salutate i vostri testimoni: abbraccio o stretta di mano epica',
    instructionsBefore: 'Inquadratura aperta. Chiamate i vostri testimoni e fate un abbraccio/gruppo. Posate come per una foto di squadra!',
    instructionsAfter: 'Rifate la stessa scena con i veri testimoni il giorno del matrimonio. Stessa posa, stessi abbracci, ma ora siete davvero sposati!',
    tags: ['amici', 'divertente'],
  },
  {
    id: 'discorso',
    emoji: '🎤',
    title: 'Il Brindisi',
    desc: 'Alzate il bicchiere prima del discorso: prove vs brindisi vero',
    instructionsBefore: 'Inquadratura dal basso. Prendete un bicchiere, guardate la telecamera, fate finta di fare un discorso. Muovete le mani, ridete.',
    instructionsAfter: 'Riprendete il momento del brindisi/discorso al ricevimento. Stessa inquadratura, stesse mani che gesticolano, ma le parole sono vere!',
    tags: ['divertente', 'facile'],
  },
  {
    id: 'calza-giarrettiera',
    emoji: '🎀',
    title: 'La Giarrettiera',
    desc: 'Il momento giarrettiera: prove imbarazzanti vs il rito vero',
    instructionsBefore: 'Lei si siede su una sedia, lui si avvicina in ginocchio. Fingete il gesto... ma ridete prima di iniziare!',
    instructionsAfter: 'Il momento vero! Stessa sedia, stesso lui in ginocchio, ma l\'atmosfera è elettrica. Le damigelle incitano!',
    tags: ['divertente', 'tradizione'],
  },
  {
    id: 'cambio-abito',
    emoji: '👗',
    title: 'Il Cambio d\'Abbito',
    desc: 'Transizione fulminea: abito civile → abito da cerimonia in un taglio',
    instructionsBefore: 'Inquadratura fissa. Partite in abito normale. Fate finta di "cambiarvi" passando dietro un muro/porta. Uscite con lo stesso abito ma gesto diverso.',
    instructionsAfter: 'Stessa inquadratura, stessa dinamica. Stavolta passate dietro e uscite con l\'abito da sposa/sposo. Effetto transizione puro!',
    tags: ['social', 'trend', 'facile'],
  },
  {
    id: 'coreografia',
    emoji: '💃',
    title: 'La Coreografia',
    desc: '10 secondi di ballo: ripetete lo stesso passo prima e dopo — come su TikTok',
    instructionsBefore: 'Inquadratura frontale. Ballate 10 secondi di un passo semplice (tipo il "prometto" trend). Sorrisi e sguardo complici.',
    instructionsAfter: 'Stessa inquadratura, stessa coreografia, ma con gli abiti da cerimonia. Il contrasto è pazzesco!',
    tags: ['social', 'trend', 'divertente'],
  },
  {
    id: 'pov',
    emoji: '🎥',
    title: 'POV: Dal Fidanzamento al Matrimonio',
    desc: 'Punto di vista: la telecamera sono io che guardo te — emozione pura',
    instructionsBefore: 'Tieni il telefono come se fosse i tuoi occhi (selfie POV). Inquadra l\'altro/a che arriva e ti sorride. Giratevi insieme.',
    instructionsAfter: 'Stesso POV durante la cerimonia. Inquadra l\'altro/a che ti aspetta all\'altare. Lo sguardo è completamente diverso!',
    tags: ['social', 'emozionante', 'trend'],
  },
  {
    id: 'reazione',
    emoji: '⚡',
    title: 'La Reazione a Catena',
    desc: 'Ognuno reagisce alla notizia: dal primo che lo dice all\'ultimo che lo scopre',
    instructionsBefore: 'Inquadratevi uno per uno: il primo dice "Ci sposiamo!", il secondo reagisce, il terzo... fate una catena di reazioni a cascata.',
    instructionsAfter: 'Rifate la stessa catena il giorno del matrimonio. Stessa dinamica, ma le reazioni sono vere e le emozioni sono alle stelle!',
    tags: ['divertente', 'originale', 'famiglia'],
  },
  {
    id: 'voiceover',
    emoji: '🎙️',
    title: 'Il Voiceover',
    desc: 'Stessa voce fuori campo per due momenti diversi — effetto cinematografico',
    instructionsBefore: 'Filmato muto: fate un gesto tipo guardare lontano, sorridere, camminare. Poi registrate un voiceover dopo che dice qualcosa di romantico.',
    instructionsAfter: 'Stesso filmato muto, stessi gesti, ma durante la cerimonia. Applicate lo stesso voiceover — il significato cambia completamente!',
    tags: ['artistico', 'emozionante', 'trend'],
  },
  {
    id: 'bacio-altare',
    emoji: '💏',
    title: 'Il Bacio sull\'Altare',
    desc: 'Il bacio finale: prova generale... e quello che sigilla il SI',
    instructionsBefore: 'In piedi come all\'altare. Guardatevi, sorridete, e datevi un bacio. Non troppo lungo, non troppo corto. Perfetto.',
    instructionsAfter: 'Il bacio dopo il "Si, lo voglio"! Stessa posizione, stesso sguardo, ma è il bacio che cambia tutto. Il climax della giornata!',
    tags: ['emozionante', 'consigliato'],
  },
];

export const TAGS = ['consigliato', 'facile', 'divertente', 'emozionante', 'romantico', 'dolce', 'elegante', 'caos', 'amici', 'originale', 'tradizione'] as const;
